src/main/java/com/spring/finalproject/entity/AccountEntity.java
package com.spring.finalproject.entity;

import com.spring.finalproject.enums.UserStatus;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "account")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class AccountEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "accId")
    private long id;

    @Column(name = "fullName")
    private String fullName;

    @Column(name = "email", unique = true)
    private String email;

    @Column(name = "password", unique = true)
    private String password;

    @Column(name = "phoneNumber")
    private String phoneNumber;


    @Column(name = "address")
    private String address;

    @Column(name = "status", nullable = false)
    @Enumerated(EnumType.STRING)
    private UserStatus status = UserStatus.ACTIVE;


    @OneToMany(mappedBy = "accountEntity")
    private List<AccountRoleEntity> accountRoleEntityList;

    @OneToMany(mappedBy = "account")
    @LazyCollection(LazyCollectionOption.FALSE)
    private List<CartEntity> cartEntities;



    //getRoleUser

    public List<RolesEntity> getRoleOfAccount() {
        List<RolesEntity> roleList = new ArrayList<>();
        if (this.getAccountRoleEntityList().isEmpty()) {
            return new ArrayList<>();
        } else {
            for (AccountRoleEntity item : this.getAccountRoleEntityList()) {
                roleList.add(item.getRolesEntity());
            }
            return roleList;

        }


    }
}

src/main/webapp/WEB-INF/jsp/admin/home-admin.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Admin Page</title>
    <jsp:include page="../include/management/css-page.jsp"/>
</head>
<body class="page-header-fixed sidemenu-closed-hidelogo page-content-white page-md header-white dark-sidebar-color logo-dark">
<div class="page-wrapper">
    <div class="page-header navbar navbar-fixed-top">
        <jsp:include page="../include/management/header.jsp"/>
    </div>
    <div class="page-container">
        <jsp:include page="../include/management/manager-side.jsp"/>
        <div class="page-content-wrapper">
            <jsp:include page="../include/management/component/dashboard-1.jsp" />
        </div>
    </div>
    <jsp:include page="../include/management/component/chat-sidebar.jsp" />
    <jsp:include page="../include/management/footer.jsp"/>
</div>
<jsp:include page="../include/management/js-page.jsp" />
</body>
</html>

src/main/webapp/WEB-INF/jsp/admin/update-add-staff.jsp
<%--
  Created by IntelliJ IDEA.
  User: Admin
  Date: 10/12/22
  Time: 4:07 PM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix = "fmt" uri = "http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html lang="en">
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta name="description" content="Responsive Admin Template" />
    <meta name="author" content="SmartUniversity" />
    <title>Edit Staff</title>
    <jsp:include page="../include/management/css-page.jsp"/>
</head>
<!-- END HEAD -->
<body class="page-header-fixed sidemenu-closed-hidelogo page-content-white page-md header-white dark-sidebar-color logo-dark">
<div class="page-wrapper">
    <!-- start header -->
    <div class="page-header navbar navbar-fixed-top">
        <jsp:include page="../include/management/header.jsp"/>
    </div>
    <!-- end header -->
    <!-- start page container -->
    <div class="page-container">
        <!-- start sidebar menu -->
        <jsp:include page="../include/management/manager-side.jsp"/>
        <!-- end sidebar menu -->
        <!-- start page content -->
        <div class="page-content-wrapper">
            <div class="page-content">
                <form:form action="${pageContext.request.contextPath} ${action}" method="post" modelAttribute="account">
                <div class="page-bar">
                <c:if test="${action.equals('/admin/update-user')}">
                    <div class="page-title-breadcrumb">
                        <div class=" pull-left">
                            <div class="page-title">Edit Staff Details</div>
                        </div>

                        <ol class="breadcrumb page-breadcrumb pull-right">
                            <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="<c:url value="/admin/home-admin"/>">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
                            </li>
                            <li><a class="parent-item" href="">Staff</a>&nbsp;<i class="fa fa-angle-right"></i>
                            </li>
                            <li class="active">Edit Staff Details</li>
                        </ol>
                    </div>
                </c:if>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card-box">
                            <div class="card-head">
                                <header>Basic Information</header>
                                <button id = "panel-button"
                                        class = "mdl-button mdl-js-button mdl-button--icon pull-right"
                                        data-upgraded = ",MaterialButton">
                                    <i class = "material-icons">more_vert</i>
                                </button>
                                <ul class = "mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
                                    data-mdl-for = "panel-button">
                                    <li class = "mdl-menu__item"><i class="material-icons">assistant_photo</i>Action</li>
                                    <li class = "mdl-menu__item"><i class="material-icons">print</i>Another action</li>
                                    <li class = "mdl-menu__item"><i class="material-icons">favorite</i>Something else here</li>
                                </ul>
                            </div>
                            <div class="card-body row">
                                <c:if test="${action.equals('/admin/update-user')}">
                                <div class="col-lg-6 p-t-20">
                                    <div class = "mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
                                        <form:input path="id" type = "text" class = "mdl-textfield__input" id="id" placeholder="ID" disabled="true"/>
                                        <label class = "mdl-textfield__label">ID User</label>
                                    </div>
                                </div>
                                </c:if>
                                <div class="col-lg-6 p-t-20">
                                    <div class = "mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
                                        <form:input path="fullName" type = "text" class = "mdl-textfield__input" id="fullName" required="true"/>
                                        <label class = "mdl-textfield__label">Full Name</label>
                                    </div>
                                </div>
                                <div class="col-lg-6 p-t-20">
                                    <div class = "mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
                                        <form:input path="address" class = "mdl-textfield__input" type = "text" id = "address"/>
                                        <label class = "mdl-textfield__label" >Address</label>
                                    </div>
                                </div>
                                <div class="col-lg-6 p-t-20">
                                    <div class = "mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
                                        <form:input path="email" class = "mdl-textfield__input" type = "email" id = "email" />
                                        <label class = "mdl-textfield__label" >Email</label>
                                        <span class = "mdl-textfield__error">Enter Valid Email Address!</span>
                                    </div>
                                </div>
                                <div class="col-lg-6 p-t-20">
                                    <label class="control-label col-lg-2">Status</label>
                                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fix-height txt-full-width">
                                       <select class="form-control" name="status">
                                           <option value="">- Choose Status -</option>
                                                    <c:forEach items="${statusUser}" var="s">

                                                        <c:if test="${s == account.status}">
                                                            <option value="${s}" selected>${s}</option>
                                                        </c:if>
                                                        <c:if test="${s != account.status}">
                                                            <option value="${s}">${s}</option>
                                                        </c:if>
                                                    </c:forEach>
                                            </select>
                                    </div>
                                </div>
                                <div class="col-lg-6 p-t-20">
                                    <div class = "mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
                                        <form:input class = "mdl-textfield__input" type = "text" path="phoneNumber" id = "phoneNumber"
                                                   pattern = "-?[0-9]*(\.[0-9]+)?"/>
                                        <label class = "mdl-textfield__label" for = "phoneNumber">Mobile Number</label>
                                        <span class = "mdl-textfield__error">Number required!</span>
                                    </div>
                                </div>
                                <div class="col-lg-12 p-t-20 text-center">
                                    <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 m-r-20 btn-pink">Submit</button>
                                    <button type="reset" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 btn-default">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </form:form>
        </div>
        </div>
        <!-- end page content -->
        <!-- start chat sidebar -->
        <jsp:include page="../include/management/component/chat-sidebar.jsp" />
        <!-- end chat sidebar -->

    </div>
    <!-- end page container -->
    <!-- start footer -->
    <jsp:include page="../include/management/footer.jsp" />
    <!-- end footer -->
</div>
<jsp:include page="../include/management/js-page.jsp"/>
</body>
</html>

src/main/webapp/WEB-INF/jsp/admin/view-staff.jsp
<%--
  Created by IntelliJ IDEA.
  User: Admin
  Date: 10/12/22
  Time: 4:07 PM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix = "fmt" uri = "http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html lang="en">
<!-- BEGIN HEAD -->
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content="width=device-width, initial-scale=1" name="viewport" />
  <meta name="description" content="Responsive Admin Template" />
  <meta name="author" content="SmartUniversity" />
  <title>View Staff</title>
  <jsp:include page="../include/management/css-page.jsp"/>
</head>
<!-- END HEAD -->
<body class="page-header-fixed sidemenu-closed-hidelogo page-content-white page-md header-white dark-sidebar-color logo-dark">
<div class="page-wrapper">
  <!-- start header -->
  <div class="page-header navbar navbar-fixed-top">
    <jsp:include page="../include/management/header.jsp"/>
  </div>
  <!-- end header -->
  <!-- start page container -->
  <div class="page-container">
    <!-- start sidebar menu -->
    <jsp:include page="../include/management/manager-side.jsp"/>
    <!-- end sidebar menu -->
    <!-- start page content -->
    <div class="page-content-wrapper">
      <div class="page-content">
        <div class="page-bar">
          <div class="page-title-breadcrumb">
            <div class=" pull-left">
              <div class="page-title">All Staffs</div>
            </div>
            <ol class="breadcrumb page-breadcrumb pull-right">
              <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="<c:url value="/admin/home-admin"/>">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
              </li>
              <li><a class="parent-item" href="">Staffs</a>&nbsp;<i class="fa fa-angle-right"></i>
              </li>
              <li class="active">All Staffs</li>
            </ol>
          </div>
        </div>
        <ul class="nav nav-pills nav-pills-rose">
          <li class="nav-item tab-all"><a class="nav-link active show"
                                          href="#tab1" data-toggle="tab">List View</a></li>
        </ul>
        <div class="tab-content tab-space">
          <div class="tab-pane active show" id="tab1">
            <div class="row">
              <div class="col-md-12">
                <div class="card-box">
                  <div class="card-head">
                    <button id = "panel-button"
                            class = "mdl-button mdl-js-button mdl-button--icon pull-right"
                            data-upgraded = ",MaterialButton">
                      <i class = "material-icons">more_vert</i>
                    </button>
                    <ul class = "mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
                        data-mdl-for = "panel-button">
                      <li class = "mdl-menu__item"><i class="material-icons">assistant_photo</i>Action</li>
                      <li class = "mdl-menu__item"><i class="material-icons">print</i>Another action</li>
                      <li class = "mdl-menu__item"><i class="material-icons">favorite</i>Something else here</li>
                    </ul>
                  </div>
                  <div class="card-body ">
                    <div class="table-scrollable">
                      <c:if test="${not empty accountList}">
                      <table class="table table-hover table-checkable order-column full-width" id="example4">
                        <thead>
                        <tr>
                          <th class="center"> Full Name </th>
                          <th class="center"> Mobile </th>
                          <th class="center"> Email </th>
                          <th class="center"> Address </th>
                          <th class="center"> Status</th>
                          <th class="center"> Roles</th>
                          <th class="center"> Action </th>
                        </tr>
                        </thead>
                        <tbody>
                        <c:forEach items="${accountList}" var="a">
                        <tr class="odd gradeX">
                          <td class="center">${a.fullName}</td>
                          <td class="center"><a href="tel:${a.phoneNumber}">
                              ${a.phoneNumber} </a></td>
                          <td class="center"><a href="mailto:${a.email}">
                              ${a.email} </a></td>
                          <td class="center">${a.address}</td>

                          <td class="center">${a.status.toString()}</td>
                          <td class="center">
                            <table>
                              <c:forEach items="${a.roleOfAccount}" var="r">
                                  <td>${r.role.name()}</td>
                              </c:forEach>
                            </table>
                          </td>
                          <td class="center">
                            <button type="button"
                                    onclick="location.href = '<c:url value="/admin/update-user/${a.id}"/>'"
                                    class="mdl-button mdl-js-button mdl-button--primary margin-right-10">
                              <i class="fa fa-pencil"></i>
                            </button>
                            <button type="button"
                                    onclick="location.href = '<c:url value="/admin/delete-user/${a.id}"/>'"
                                    class="btn btn-tbl-delete btn-xs">
                              <i class="fa fa-trash-o "></i>
                            </button>
                          </td>
                        </tr>
                        </c:forEach>
                        </tbody>
                      </table>
                      </c:if>
                      <c:if test="${accountList.size()==0}">
                        <div>
                          <p style="color: red; text-align: center;font-size: 20px;">
                            There is no data
                          </p>
                        </div>
                      </c:if>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end page content -->
    <!-- start chat sidebar -->
    <jsp:include page="../include/management/component/chat-sidebar.jsp" />
    <!-- end chat sidebar -->

  </div>
  <!-- end page container -->
  <!-- start footer -->
  <jsp:include page="../include/management/footer.jsp" />
  <!-- end footer -->
</div>
<jsp:include page="../include/management/js-page.jsp"/>
</body>
</html>